baseURL = 'https://vernonit.com/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'VernonIT'
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = 'github.com/imfing/hextra'

[params]
  description = 'Full-lifecycle product engineering. Web apps, platforms, and backend infrastructure.'

  [params.author]
    name = 'David Vernon'
    email = ''

  [params.theme]
    default = 'system'
    displayToggle = true

  [params.navbar]
    displayTitle = false
    displayLogo = true

    [params.navbar.logo]
      path = '/vernonit-signature.svg'
      link = '/'


  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = false

  [params.search]
    enable = true
    type = 'flexsearch'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'monokai'

[[menu.main]]
  name = 'About'
  pageRef = '/about'
  weight = 10

[[menu.main]]
  name = 'Blog'
  pageRef = '/posts'
  weight = 20
