baseURL = 'https://vernonit.com/'
languageCode = 'en-us'
title = 'VernonIT'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[module]
  [[module.imports]]
    path = 'github.com/imfing/hextra'

[params]
  description = 'Full-lifecycle product engineering. Web apps, platforms, and backend infrastructure.'
  author = 'David Vernon'

  [params.navbar]
    displayTitle = true
    displayLogo = false

  [params.footer]
    enable = true

  [params.search]
    enable = true
    type = 'flexsearch'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'monokai'
